# Generated by Django 4.0.4 on 2022-05-12 09:20

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
