# Generated by Django 4.0.4 on 2022-05-04 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_auth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "status",
                    models.BooleanField(
                        choices=[
                            (False, "Not Completed"),
                            (True, "Completed"),
                        ],
                        default=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_auth.user",
                    ),
                ),
            ],
        ),
    ]
