# Generated by Django 4.0.4 on 2022-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
